<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "awit_cl_media_db"
 *
 * Auto generated by Extension Builder 2014-11-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CL Media DB',
	'description' => 'to do',
	'category' => 'plugin',
	'author' => 'A. Werner',
	'author_email' => 'a.werner@awit.biz',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'extbase' => '6.2',
			'fluid' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);